In [4]:
import numpy as np

# buat vector x_np dengan ukuran 3x1
x_np = np.array([[57], [75], [27]])
print(x_np)

[[57]
 [75]
 [27]]


In [5]:
# buat vektor y_np dengan ukuran 3x1
y_np = np.array([[19], [46], [29]])
print(y_np)

[[19]
 [46]
 [29]]


In [6]:
# hitung panjang vector x_np
len(x_np)

3

In [7]:
# tampilkan ukuran vector x_np
x_np.shape

(3, 1)

In [8]:
# tampilkan ukuran vector x_np
x_np.shape

(3, 1)

In [9]:
# akses elemen pertama dari vector x_np
x_np[0]

array([57])

In [10]:
# tampilkan tipe data elemen pertama dari vector x_np
x_np[0].dtype

dtype('int64')

In [11]:
# lakukan transpose pada vector x_np dan simpan pada variabel x_t
x_t = x_np.T
print(x_t)

[[57 75 27]]


In [12]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [13]:
# lakukan transpose pada vector y_np dan simpan pada variabel y_t
y_t = y_np.T
print(y_t)

[[19 46 29]]


In [14]:
import torch as pt

# buat vector x_pt dengan ukuran 3x1 menggunakan pytorch dan ukuran dari vector x_pt
x_pt = pt.tensor([57, 75, 27])
print(x_pt)
x_pt.shape

tensor([57, 75, 27])


torch.Size([3])

In [15]:
# buat vector y_pt dengan ukuran 3x1 menggunakan pytorch dan ukuran dari vector y_pt
y_pt = pt.tensor([19, 46, 29])
print(y_pt)
y_pt.shape

tensor([19, 46, 29])


torch.Size([3])

In [16]:
# lakukan transpose pada vector x_pt dan simpan pada variabel x_pT
x_pT = x_pt.T
print(x_pT)
x_pT.shape

tensor([57, 75, 27])


/tmp/ipykernel_8699/2924804590.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  x_pT = x_pt.T


torch.Size([3])

In [17]:
import tensorflow as tf

# buat vector x_pt dengan ukuran 3x1 menggunakan tensorflow dan ukuran dari vector x_pt
x_tf = tf.Variable([57, 75, 27], dtype = tf.int32)
print(x_tf)
x_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([57, 75, 27], dtype=int32)>


TensorShape([3])

In [18]:
# buat vector y_pt dengan ukuran 3x1 menggunakan tensorflow dan ukuran dari vector y_pt
y_tf = tf.Variable([19, 46, 29], dtype = tf.int32)
print(y_tf)
y_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([19, 46, 29], dtype=int32)>


TensorShape([3])

In [19]:
# lakukan transpose pada vector x_tf dan simpan pada variabel x_tF
x_tF = tf.transpose(x_tf)
print(x_tF)
x_tF.shape

tf.Tensor([57 75 27], shape=(3,), dtype=int32)


TensorShape([3])